### ISSUE TITLE
Menu bar not showing up

### ISSUE THREAD

**Issue by akg2000** [yenchiah/project-website-template#17]
Hi in the latest version, the menu bar isn't showing up. Can you please check?

Thanks

**Comment by yenchiah** [comment]
Hi, could you also let me know the browser (e.g. Chrome, Safari), device type (desktop or mobile), and the OS (e.g. macOS 10.15, Android 10) that you saw this problem, please? Thank you for reporting this issue.

**Comment by akg2000** [comment]
Hi, I am using windows 10 version - 20H2, and chrome - Version 87.0.4280.88 (Official Build) (64-bit) on a laptop.

**Comment by yenchiah** [comment]
Thanks. Could you also let me know which menu bar that you refer to? Is it the menu bar at the top of the demo webpage (yenchiah.github.io/project-website-template/)? Or is it the dropdown menu on the widget page (yenchiah.github.io/project-website-template/widgets.html)?

**Comment by akg2000** [comment]
hi, sorry for the delay. It is the menu bar at the top(menu.html)

btw, Happy New Year.

**Comment by yenchiah** [comment]
Hmmm... I checked the template website using a Windows 10 Chrome browser, but I did not see the problem. If you could share your webpage, I could take a quick look and see if there are problems that are obvious.

**Comment by christycoon** [comment]
Thanks yenchiah for this great template. I was getting the same issue. The menu bar is not displaying. 

This is the error I get in console. Any idea what can be the issue here?

<img width="486" alt="Screen Shot 2021-02-04 at 6 47 16 PM" src="https://user-images.githubusercontent.com/5744999/106900140-2b695280-671c-11eb-92f5-a11681d253ae.png">

**Comment by yenchiah** [comment]
Hmmm... I think it is because the Cross-Origin Resource Sharing policy does not allow loading the menu.html file via JavaScript when you open the page from your local file (your URL begins with "file://" but not "https://"). I would suggest using a localhost development environment to fix this problem. I have a Apache server running on my local machine for development purposes, so that is why I did not see this error.
